import Head from 'next/head'
import Link from 'next/link'
import LandingPage from '../components/LandingPage'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Study Sticks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex'>
        <div className='text-white h-screen w-screen' style={{background: 'rgb(31 40 62)'}}>
		<LandingPage/>
		<Link href={'/signup'}>
			<button className='text-3xl mt-20 p-4 bg-teal-400 mx-20 rounded-xl'>Hello World</button>
		</Link>
  </div> 
      </main>
    </div>
  )
}
